version: "3"

services:
  app:
    build: .
    container_name: sumula-app
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
